version: "3.7"

services:
  server-1:
    build: 
      context: server-1
    container_name: server-1
    ports: 
      - 1501:1501
  
  server-2:
    build: 
      context: server-2
    container_name: server-2
    ports: 
      - 1502:1502

  server-3:
    build: 
      context: server-3
    container_name: server-3
    ports: 
      - 1503:1503

  load-balancer:
    image: nginx
    container_name: load-balancer
    ports:
      - 1500:80
    depends_on:
      - server-1
      - server-2
      - server-3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
